@startuml
'https://plantuml.com/component-diagram'

[Ticket Endpoint] <<..com.example.archunitspring.presentation.endpoints.TicketEndpoint..>> as ticketendpoint #white/PowderBlue
[PlaneTicketService] <<..com.example.archunitspring.application.services.PlaneTicketServiceImpl..>> as planeticketservice #white/PowderBlue
[TicketService] <<..com.example.archunitspring.application.interfaces.TicketService..>> as ticketservice #white/Green

planeticketservice -> ticketservice : implements
ticketendpoint <-- ticketservice
@enduml